/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fordalog_in;

//imports
import java.awt.Color;
import java.util.regex.Pattern;
//====================

public class Sign_InFormStep2 extends javax.swing.JFrame {

    /**
     * Creates new form Sign_InFormStep2
     */
    public Sign_InFormStep2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        MiddleName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        LastName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ProceedButton = new javax.swing.JButton();
        PreviousButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign-In");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Step 2 out of 3");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name:");

        FirstName.setBackground(new java.awt.Color(51, 51, 51));
        FirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));

        MiddleName.setBackground(new java.awt.Color(51, 51, 51));
        MiddleName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        MiddleName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Middle Name or Inital:");

        LastName.setBackground(new java.awt.Color(51, 51, 51));
        LastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last Name:");

        ProceedButton.setText("Proceed");
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        PreviousButton.setText("Previous");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PreviousButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProceedButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(MiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProceedButton)
                    .addComponent(PreviousButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sign_In_BG4.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 80, 352, 420));

        jLabel8.setFont(new java.awt.Font("Segoe Script", 1, 52)); // NOI18N
        jLabel8.setText("Citizen's");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(378, 14, -1, 61));

        jLabel7.setFont(new java.awt.Font("Monospaced", 1, 52)); // NOI18N
        jLabel7.setText("Records");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Sign_InhubBG.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        Sign_InForm SignInFrame = new Sign_InForm();
        SignInFrame.setVisible(true);
        SignInFrame.pack();
        SignInFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
          //Name deniers
          String DenyCharInputs = ".*[@$%&*#1234567890].*";
          Pattern DenyCharRegex = Pattern.compile(DenyCharInputs);
          //==========================
          
          //Name Inputs
          String FirstNameInput = FirstName.getText();
          String MiddleNameInput = MiddleName.getText();
          String LastNameInput = LastName.getText();
          //===========================
          
          //Valid Checker
          boolean ValidFirstName = true;
          boolean ValidMiddleName = true;
          boolean ValidLastName = true;
          //============================
          
          //First Name Checker
          if (FirstNameInput.isEmpty())
          {
              FirstName.setText("Please enter your First Name");
              FirstName.setForeground(Color.red);
              ValidFirstName = false;
          }
          
          else if (DenyCharRegex.matcher(FirstNameInput).matches())
          {
              FirstName.setText("Invalid Characters!");
              FirstName.setForeground(Color.RED);
              ValidFirstName = false;
          }
          
          else
          {             
              //Reset to Default
              FirstName.setText("");
              FirstName.setForeground(Color.WHITE);          
          }
          
          //Middle Name Checker
          if (MiddleNameInput.isEmpty())
          {
              MiddleName.setText("Please enter your Middle Name");
              MiddleName.setForeground(Color.RED);
              ValidMiddleName = false;
          }
          
          else if (DenyCharRegex.matcher(MiddleNameInput).matches())
          {
              MiddleName.setText("Invalid Characters!");
              MiddleName.setForeground(Color.RED);
              ValidMiddleName = false;
          }
          
          else
          {
              //Reset to default
              MiddleName.setText("");
              MiddleName.setForeground(Color.WHITE);
          }
          
          //Last Name Checker
          if (LastNameInput.isEmpty())
          {
              LastName.setText("Please enter your Last Name");
              LastName.setForeground(Color.RED);
              ValidLastName = true;
          }
          
          else if (DenyCharRegex.matcher(LastNameInput).matches())
          {
              LastName.setText("Invalid Characters!");
              LastName.setForeground(Color.RED);
              ValidLastName = false;
          }
          
          else
          {
              //reset to default
              LastName.setText("");
              LastName.setForeground(Color.WHITE);
          }
          
          //Proceed to next step
          if (ValidFirstName && ValidMiddleName && ValidLastName)
          {
              Sign_InFormStep3 stepThree = new Sign_InFormStep3 ();
              stepThree.setVisible(true);
              stepThree.pack();
              stepThree.setLocationRelativeTo(null);
              this.dispose();
          }
    }//GEN-LAST:event_ProceedButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MiddleName;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
